import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { getDashboardStats, getRecentActivity } from '../services/userService.js';
import { healthcheck } from '../services/healthService.js';
import { deleteGoal } from '../services/goalService.js';
import { getGoals } from '../services/goalService.js';
import Button from '../components/ui/Button.jsx';
import Spinner from '../components/ui/Spinner.jsx';
import GoalCard from '../components/GoalCard.jsx';
import EmptyState from '../components/ui/EmptyState.jsx';

export default function Dashboard() {
    const [stats, setStats] = useState(null); const [activity, setActivity] = useState([]); const [goals, setGoals] = useState([]); const [serverHealthy, setServerHealthy] = useState(null); const [loading, setLoading] = useState(true);
    const load = async () => { setLoading(true); try { const [s, a, g, health] = await Promise.all([getDashboardStats(), getRecentActivity(6), getGoals({ limit: 4, offset: 0, order_by: 'deadline', order: 'asc' }), healthcheck()]); setStats(s); setActivity(a); setGoals(g); setServerHealthy(Boolean(health.health)); } finally { setLoading(false); } };
    useEffect(() => { load(); }, []);
    const totalBest = useMemo(() => (stats?.best_habits_by_value || []).length, [stats]);
    if (loading) return <Spinner />;
    return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-widest text-indigo-600">Добро пожаловать</p><h1 className="mt-1 text-3xl font-black tracking-tight">Ваш прогресс</h1><p className="mt-2 text-sm text-slate-500">Главные показатели и ближайшие цели — на одном экране.</p></div><Link to="/goals"><Button>+ Новая цель</Button></Link></div><div className="flex items-center gap-2 text-xs font-semibold text-slate-400"><span className={`h-2 w-2 rounded-full ${serverHealthy ? 'bg-emerald-500' : 'bg-rose-500'}`} />API {serverHealthy ? 'работает' : 'недоступен'}</div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Завершено целей" value={`${stats?.goals_completed_percent ?? 0}%`} icon="🎯" /><Stat label="Макс. серия" value={`${stats?.max_streak ?? 0} дн.`} icon="🔥" /><Stat label="Сильных привычек" value={totalBest} icon="⚡" /><Stat label="Записей активности" value={activity.length} icon="📝" /></div><div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-black">Ближайшие цели</h2><p className="text-xs text-slate-400">Сортировка по дедлайну</p></div><Link to="/goals" className="text-sm font-bold text-indigo-600">Все цели →</Link></div>{goals.length ? <div className="grid gap-4 md:grid-cols-2">{goals.map((goal) => <GoalCard key={goal.id} goal={goal} onDelete={async (goalId) => { if (!window.confirm('Удалить цель?')) return; await deleteGoal(goalId); await load(); }} />)}</div> : <EmptyState title="Пока нет целей" description="Создайте первую цель, чтобы начать отслеживание." action={<Link to="/goals"><Button>Создать цель</Button></Link>} />}</section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-black">Последняя активность</h2><p className="mt-1 text-xs text-slate-400">Заметки из последних записей прогресса</p><div className="mt-5 space-y-3">{activity.length ? activity.map((item, index) => <div key={`${item}-${index}`} className="rounded-2xl bg-slate-50 p-3 text-sm text-slate-600"><span className="mr-2 font-bold text-indigo-500">{index + 1}</span>{item || 'Запись без заметки'}</div>) : <p className="py-8 text-center text-sm text-slate-400">Активности пока нет.</p>}</div></section></div></div>;
}
function Stat({ label, value, icon }) { return <div className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-2xl">{icon}</span><span className="text-2xl font-black text-slate-900">{value}</span></div><p className="mt-3 text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p></div>; }
